POST http://localhost:5000/api/url/shorten
Content-Type : application/json

{
    "longUrl" : "https://www.google.com/search?q=images&safe=active&sxsrf=ALeKk01_lBcpLfLywPTrddNDiSURvnGF-w:1585466573628&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj6oLKfk7_oAhUy4zgGHaJBAaYQ_AUoAXoECA0QAw&biw=1536&bih=754#imgrc=04An0H0KqVMhCM"
}